 server:
   port: 8080
   # needed for swagger-ui to detect correct proxied paths correctly.
   # Configuration needed for the [Try out] buttons to work
   # this works in combination with the proxied headers
   # proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
   # proxy_set_header X-Forwarded-Prefix /services/impower-facilioo;
   forward-headers-strategy: FRAMEWORK

 spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://13.60.203.205:8443/realms/APIREST