server:
  port: 8080
  forward-headers-strategy: framework

spring:
  application:
    name: progetto
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://13.60.203.205:8443/realms/APIREST
