server:
  port: 8080
  forward-headers-strategy: framework

spring:
  application:
    name: progetto
  datasource:
    url: ${DB_URL:jdbc:h2:mem:progetto;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
    driver-class-name: ${DB_DRIVER:org.h2.Driver}
  sql:
    init:
      mode: never
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://13.60.203.205:8443/realms/APIREST
